name: JMeter Performance Test

on:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21.0.2+13.0.LTS'

    - name: Download JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xf apache-jmeter-5.4.1.tgz

    - name: Run JMeter Test
      run: |
        apache-jmeter-5.4.1/bin/jmeter -n -t FirstTestPlan.jmx -l results.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: results.jtl
